chore: auto publish to npm, closes #106
simplycubed/extensions pull request #110
Opened 2023-01-21 20:07 UTC by anasmuhmd

2023-01-21 20:27 UTC, charlesgreen requested changes
@anasmuhmd this will push a new release to npm even if there are no changes to webflow-utils. 

I think we should change the approach to publish to npm when a new GitHub Release is created.  

https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry

2023-01-21 20:54 UTC, anasmuhmd commented
> @anasmuhmd this will push a new release to npm even if there are no changes to webflow-utils.

@charlesgreen The trigger will only publish when if there is a version (Logic is inside scripts/npm_publish.sh)

> I think we should change the approach to publish to npm when a new GitHub Release is created.
> 
> https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry

@charlesgreen sounds ok, but we would be triggering publish action unnecessarily on every release. Because every release doesn't trigger a publish to npm. I'm not sure if there is way to check if release is for webflow-utils package.

2023-01-22 08:37 UTC, charlesgreen commented
Hi @anasmuhmd  Thanks for the replies. It took some time to look at the options. 
I agree that if we only use Github Actions it is difficult to know which packages are published, etc.

We can use the Lerna binary to drive the version updates, create GitHub Releases for each package, and publish the public packages to npm (Lerna knows only to publish packages set to public in the package.json) to npm. 

The open question is if we connect it to GitHub Actions or not to make it a manual or automatic process. 
I found an article with a code repo including the implementation using GitHub Actions.

- https://dev.to/xcanchal/automatic-versioning-in-a-lerna-monorepo-using-github-actions-4hij
- https://github.com/xcanchal/monorepo

There is a small change as they also support a development branch (beta release) and a main branch (production release) which I think might be a good idea to follow as well. 

Please have a look and let me know your thoughts.

2023-01-23 18:59 UTC, anasmuhmd commented
> * https://github.com/xcanchal/monorepo

https://dev.to/xcanchal/automatic-versioning-in-a-lerna-monorepo-using-github-actions-4hij looks good to me. we can use the same approach.

2023-01-24 03:53 UTC, charlesgreen commented
@anasmuhmd I agree. Please make the needed changes to follow the monorepo approach.

2023-01-24 15:22 UTC, charlesgreen commented
@anasmuhmd, the mono repo also uses a main and dev branch to publish a final and beta release. 
I'm thinking we might also want to do that. What do you think?

2023-01-27 15:55 UTC, charlesgreen commented
@anasmuhmd I'm not sure the current status of this ticket, given the new approach. Please let me know.

2023-01-28 06:53 UTC, anasmuhmd commented
@charlesgreen I haven't updated yet.

2023-02-05 00:11 UTC, charlesgreen requested changes
@anasmuhmd I don't see it in the code but guessing that the flow also updates the tags on the GitHub repo and creates a release there as well.

My understanding is that lerna respects the package.json files so that only the webflow-utils repo will be published to NPM. 

Please let me know if my understanding is incorrect.

2023-02-05 00:11 UTC, charlesgreen commented on .github/workflows/publish.yml
> +          node-version: "14"
Update to use `actions/setup-node@v3` with Node 16

https://github.com/actions/setup-node

2023-02-05 00:11 UTC, charlesgreen commented on .github/workflows/publish.yml
> +      - name: "Checkout"
Update to use `actions/checkout@v3` with Node 16

https://github.com/actions/setup-node

2023-02-05 18:08 UTC, anasmuhmd commented
> @anasmuhmd I don't see it in the code but guessing that the flow also updates the tags on the GitHub repo and creates a release there as well.

For github release, we need to add the option '--create-release github'. I tried testing this in a different repo, I couldn't successfully do it.

> My understanding is that lerna respects the package.json files so that only the webflow-utils repo will be published to NPM.

Yes, I think so. I haven't tested it.

2023-02-05 18:17 UTC, anasmuhmd commented
> @anasmuhmd I don't see it in the code but guessing that the flow also updates the tags on the GitHub repo and creates a release there as well.
> 
> My understanding is that lerna respects the package.json files so that only the webflow-utils repo will be published to NPM.
> 
> Please let me know if my understanding is incorrect.

Create Release option is added as well. Yes, only private packages are published.

2023-02-05 22:34 UTC, charlesgreen approved these changes

2023-02-05 22:34 UTC, merged