feat: update extension.yaml
simplycubed/extensions pull request #28
Opened 2022-12-21 16:12 UTC by anasmuhmd

2022-12-21 23:02 UTC, charlesgreen requested changes

2022-12-22 23:49 UTC, charlesgreen requested changes
See comments.

2022-12-23 07:33 UTC, anasmuhmd commented on webflow-events/extension.yaml
>      type: string
Done: https://github.com/simplycubed/extensions/pull/28/commits/c4b0fb4f50c69c24b1157fe7da8dd4c7ad1b8b0c

2022-12-23 07:33 UTC, anasmuhmd commented on webflow-events/extension.yaml
>      type: string
Done: https://github.com/simplycubed/extensions/pull/28/commits/c4b0fb4f50c69c24b1157fe7da8dd4c7ad1b8b0c

2022-12-23 07:58 UTC, charlesgreen approved these changes

2022-12-23 07:59 UTC, merged